//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historys
    {
        public int HistoryID { get; set; }
        public int QuestionID { get; set; }
        public string UserAnswer { get; set; }
        public int SubjectID { get; set; }
        public string UserID { get; set; }
        public bool IsCorrect { get; set; }
        public int ChallengeTime { get; set; }
        public int CorrectAnswerCount { get; set; }
        public System.DateTime TestDay { get; set; }
    }
}
