//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProgress
    {
        public int ProgressID { get; set; }
        public System.Guid UserID { get; set; }
        public int SubjectID { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public int ChallengeTimes { get; set; }
    
        public virtual subjects subjects { get; set; }
    }
}
