//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    
    public partial class QuestionEntities : DbContext
    {
        public QuestionEntities()
            : base("name=QuestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ExamResult> ExamResult { get; set; }
        public virtual DbSet<Historys> Historys { get; set; }
        public virtual DbSet<MemberProgress> MemberProgress { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<subjects> subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TemporaryProgress> TemporaryProgress { get; set; }
    }
}
